algoritmo "EX88"
var
   A,X:caractere
   Q,C:inteiro
   Procedimento Gerador(A:caractere)
   inicio
         ESCREVAL("+----===----+")
         Para C <- 1 ate Q faca
         escreval(A)
         fimpara
         ESCREVAL("+----===----+")
   fimprocedimento
inicio
      escreva("O que você quer escrever? ")
      leia(X)
      escreva("Quantas vezes? ")
      leia(Q)
      Gerador(X)

fimalgoritmo