algoritmo "semnome"
var
A: Real
B: Real
C: Real
R1: real
R2: Real
D: real
inicio
escreva ("Informe valor de A: ")
leia (A)
escreva ("Infrome valor de B: ")
leia (B)
escreva ("Informe valor de C: ")
leia (C)
D <- (B^2) - (4*A*C)
escreval ("O valor de Delta é: ", D)
R1 <- ((-B+(RaizQ(D)))/2*A)
escreval("O valor de X1 é: " , R1)
R2 <- ((-B-(RaizQ(D)))/2*A)
escreva ("O valor de X2 é: " , R2)
fimalgoritmo